
export class IncomingBatches{

    constructor(
        public id : string,
        public batch_id : string ,
        public node_id : string ,
        public channel_id : string ,
        public status : string ,
        public error_flag : string ,
        public sql_state : string ,
        public sql_code : string ,
        public sql_message : string ,
        public last_update_hostname : string ,
        public last_update_time : string ,
        public create_time : string ,
        public summary : string ,
        public ignore_count : string ,
        public byte_count : string ,
        public load_flag : string ,
        public extract_count : string ,
        public sent_count : string ,
        public load_count : string ,
        public reload_row_count : string ,
        public other_row_count : string ,
        public data_row_count : string ,
        public extract_row_count : string ,
        public load_row_count : string ,
        public data_insert_row_count : string ,
        public data_update_row_count : string ,
        public data_delete_row_count : string ,
        public extract_insert_row_count : string ,
        public extract_update_row_count : string ,
        public extract_delete_row_count : string ,
        public load_insert_row_count : string ,
        public load_update_row_count : string ,
        public load_delete_row_count : string ,
        public network_millis : string ,
        public filter_millis : string ,
        public load_millis : string ,
        public router_millis : string ,
        public extract_millis : string ,
        public transform_extract_millis : string ,
        public transform_load_millis : string ,
        public load_id : string ,
        public common_flag : string ,
        public fallback_insert_count : string ,
        public fallback_update_count : string ,
        public ignore_row_count : string ,
        public missing_delete_count : string ,
        public skip_count : string ,
        public failed_row_number : string ,
        public failed_line_number : string ,
        public failed_data_id : string
    ){}
}