
export let columnsList = [
    {name: 'Trigger id', property: "id"},
    {name: 'Source catalog', property: "source_catalog_name"},
    {name: 'Source schema', property: "source_schema_name"},
    {name: 'Source table', property: "source_table_name"},
    {name: 'channel', property: "channel_id"},
    {name: 'Sync on insert', property: "sync_on_insert"},
    {name: 'Sync on update', property: "sync_on_update"},
    {name: 'Sunc on delete', property: "sync_on_delete"},
    {name: 'Sunc on incomming batch', property: "sync_on_incoming_batch"},
    {name: 'Name for insert trigger', property: "name_for_insert_trigger"},
    {name: 'Name for update trigger', property: "name_for_update_trigger"},
    {name: 'Name for delete trigger', property: "name_for_delete_trigger"},
    {name: 'Reload channel id', property: "reload_channel_id"},
    {name: 'Sync on insert condition', property: "sync_on_insert_condition"},
    {name: 'Sync on update condition', property: "sync_on_update_condition"},
    {name: 'Sync on delete condition', property: "sync_on_delete_condition"},
    {name: 'Custom before insert text', property: "custom_before_insert_text"},
    {name: 'Custom before update text', property: "custom_before_update_text"},
    {name: 'Custom before delete text', property: "custom_before_delete_text"},
    {name: 'Custom insert trigger text', property: "custom_on_insert_text"},
    {name: 'Custom update trigger text', property: "custom_on_update_text"},
    {name: 'Custom delete trigger text', property: "custom_on_delete_text"},
    {name: 'Stream lobs', property: "use_stream_lobs"},
    {name: 'Capture Lobs', property: "use_capture_lobs"},
    {name: 'Capture old data', property: "use_capture_old_data"},
    {name: 'Stream row', property: "stream_row"},
    {name: 'Handle key update', property: "use_handle_key_updates"},
    {name: 'External select', property: "external_select"},
    {name: 'Excluded column names', property: "excluded_column_names"},
    {name: 'Included column names', property: "included_column_names"},
    {name: 'Sync key names', property: "sync_key_names"},
    {name: 'Text id expression', property: "tx_id_expression"},
    {name: 'Channel expression', property: "channel_expression"},
    {name: 'Last update', property: "last_update_time"},
    {name: 'Last update by', property: "last_update_by"},
    {name: 'Created', property: "create_time"},
    {name: 'Description', property: "description"},

];
