
export let columnsList = [
    {name: 'Channel id', property: "id"},
    {name: 'Processing order', property: "processing_order"},
    {name: 'Batch Algorithm', property: "batch_algorithm"},
    {name: 'Batch size', property: "max_batch_size"},
    {name: 'Batch to send', property: "max_batch_to_send"},
    {name: 'Data to route', property: "max_data_to_route"},
    {name: 'Extract period millis', property: "extract_period_millis"},
    {name: 'Max kbps', property: "max_network_kbps"},
    {name: 'Data loader type', property: "data_loader_type"},
    {name: 'Queue name', property: "queue"},
    {name: 'Group link direction', property: "data_event_action"},
    {name: 'Description', property: "description"},
    {name: 'Enabled', property: "enabled"},
    {name: 'Reload channel', property: "reload_flag"},
    {name: 'File sync channel', property: "file_sync_flag"},
    {name: 'Use Old Data to Route', property: "use_old_data_to_route"},
    {name: 'Use Row Data to Route', property: "use_row_data_to_route"},
    {name: 'Use Primary Key (PK) Data to Route', property: "use_pk_data_to_route"},
    {name: 'Tables Contains Big Lobs', property: "contains_big_lob"},
    {name: 'Last update', property: "last_update_time"},
    {name: 'Last update by', property: "last_update_by"},
    {name: 'Created', property: "create_time"},
];
